/*
  _____ _ _ _                    _             _       
 |  ___(_) | |_ ___ _ __   _ __ | |_   _  __ _(_)_ __  
 | |_  | | | __/ _ \ '__| | '_ \| | | | |/ _` | | '_ \ 
 |  _| | | | ||  __/ |    | |_) | | |_| | (_| | | | | |
 |_|   |_|_|\__\___|_|    | .__/|_|\__,_|\__, |_|_| |_|
                          |_|            |___/         
# A Template for Tuner_pluginPlugin, a Filter Plugin
# Generated by the command: plugin -t filter -d tuner_plugin tuner_plugin -o
# Hostname: novo
# Current working directory: /home/leo/Desktop/Workspace/dedalus-workspace
# Creation date: 2026-07-17T09:06:09.564+0200
# NOTICE: MADS Version 2.3.1
*/
// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

// other includes as needed here
#include "tuner.hpp"

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "tuner_plugin"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class Tuner_pluginPlugin : public Filter<json, json> {

public:
  // Don't forget to inherit the constructors of the parent class
  // If you really need to implement your own constructor, make sure to call 
  // the parent constructor. Normally, use set_params() to set the parameters
  // instead of the constructor.
  using Filter::Filter; // inherit constructors

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid, go to process
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    
    if (!_is_tuning_active || _current_phase == TUNE_DONE) return return_type::retry;
            
    std::string target_key;
    int real_idx = 0;
    switch (_current_phase) {
      case TUNE_X: target_key = "x"; real_idx = 0; break;
      case TUNE_Y: target_key = "y"; real_idx = 1; break;
      case TUNE_A: target_key = "a"; real_idx = 3; break;
      case TUNE_C: target_key = "c"; real_idx = 4; break;
    }

    if (topic == "setpoint" && input.contains("spi_input")) {
      if (input["spi_input"].contains(target_key)) {
        _target_k_minus_1 = _target_k;
        _target_k = input["spi_input"][target_key];
      }
    }

    else if (topic == "machine" && input.contains("position")) {
      if (input["position"].is_array() && input["position"].size() > real_idx) {
        
        float real = input["position"][real_idx];
        _tuner.log_data(_target_k_minus_1, real);

        if (std::abs(_target_k_minus_1 - _last_target) < 0.0001f) {
          _stationary_counter++;
        } else {
          _stationary_counter = 0;
        }
        _last_target = _target_k_minus_1;

        if (_stationary_counter > 500 && _tuner.full_buffer()) {
          return return_type::success; 
        }
      }
    }

    return return_type::retry;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  // Return types:
  // return_type::success: result is published
  // return_type::retry: don't publish, go to next loop
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: _error is traced via register_event, don't publish
  // return_type::critical: execution stops
  return_type process(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();

    TuningParams old_params = _tuner.get_p();
    TuningParams new_params = _tuner.process_iteration();
    float current_cost = _tuner.get_last_cost();
    _glob_counter++;

    string axis_str;
    if (_current_phase == TUNE_X) axis_str = "x";
    else if (_current_phase == TUNE_Y) axis_str = "y";
    else if (_current_phase == TUNE_A) axis_str = "a";
    else if (_current_phase == TUNE_C) axis_str = "c";

    out["command"] = "update_pids";
    out["axis"] = axis_str;
    out["kp"] = new_params.kp;
    out["ki"] = new_params.ki;
    out["kd"] = new_params.kd;
    out["kv"] = new_params.kv;
    out["ka"] = new_params.ka;
    
    /*
    Action states
    REDO = 2
    OK = 1
    IDLE = 0
    */
    
    // check global tolerance
    bool target_reached = (current_cost < 0.05f);
    // check params tolerance
    float delta_kp = abs(new_params.kp - old_params.kp);
    float delta_kv = abs(new_params.kv - old_params.kv);
    bool parameters_stagnated = (delta_kp < 0.005f && delta_kv < 0.001f);
    // check iterations number
    bool timeout_reached = (_glob_counter > 10);

    if (target_reached || parameters_stagnated || timeout_reached) {

      switch(_current_phase){

        case TUNE_X:
          _current_phase = TUNE_Y;
          out["action"] = "LOAD_GCODE_Y";
          break;
        case TUNE_Y:
          _current_phase = TUNE_A;
          out["action"] = "LOAD_GCODE_A";
          break;
        case TUNE_A:
          _current_phase = TUNE_C;
          out["action"] = "LOAD_GCODE_C";
          break;
        case TUNE_C:
          _current_phase = TUNE_DONE;
        case TUNE_DONE:
          _is_tuning_active = false;
          out["action"] = "DONE";
      }

      if (_current_phase != TUNE_DONE) {
        setup_tuner_for_current_phase(); 
      }
    } else{

      out["action"] = "REDO_GCODE";
    }

    _tuner.reset();
    _stationary_counter = 0;

    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }
  
  void set_params(const json &params) override {
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Filter::set_params(params);

    // provide sensible defaults for the parameters by setting e.g.
    _params["some_field"] = "default_value";
    // more here...

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(params);
      
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {};
    
  };

private:

  enum TuningPhase {
    TUNE_X,
    TUNE_Y,
    TUNE_A,
    TUNE_C,
    TUNE_DONE
  };
 
  TuningPhase _current_phase = TUNE_X;
  Tuner _tuner = Tuner({1.0f, 0.0f, 0.0f, 0.1f, 0.01f});
  float _last_target = 0.0f;
  int _stationary_counter = 0;
  bool _is_tuning_active = true;

  double _glob_counter = 0;

  float _target_k_minus_1;
  float _target_k;

  // fly function for selecting axes
  void setup_tuner_for_current_phase() {
    map<string, TuningBounds> bounds;
    if (_current_phase == TUNE_Y || _current_phase == TUNE_X) {
      bounds["kp"] = {0.0f, 50.0f};
      bounds["ki"] = {0.0f, 10.0f};
      bounds["kd"] = {0.0f, 500.0f};
      bounds["kv"] = {0.0f, 5.0f};
      bounds["ka"] = {0.0f, 2.0f};
    } else {
        bounds["kp"] = {0.0f, 50.0f};
        bounds["ki"] = {0.0f, 0.0f};
        bounds["kd"] = {0.0f, 0.0f};
        bounds["kv"] = {0.0f, 0.0f};
        bounds["ka"] = {0.0f, 2.0f};
    }
    
    _tuner.set_bounds(bounds);
    _tuner.reset();
    _glob_counter = 0;
  }
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(Tuner_pluginPlugin, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  Tuner_pluginPlugin plugin;
  json params;
  json input, output;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Set input data
  input["data"] = {
    {"AX", 1},
    {"AY", 2},
    {"AZ", 3}
  };

  // Set input data
  plugin.load_data(input);
  cout << "Input: " << input.dump(2) << endl;

  // Process data
  plugin.process(output);
  cout << "Output: " << output.dump(2) << endl;


  return 0;
}

