/*
  _____ _ _ _                    _             _       
 |  ___(_) | |_ ___ _ __   _ __ | |_   _  __ _(_)_ __  
 | |_  | | | __/ _ \ '__| | '_ \| | | | |/ _` | | '_ \ 
 |  _| | | | ||  __/ |    | |_) | | |_| | (_| | | | | |
 |_|   |_|_|\__\___|_|    | .__/|_|\__,_|\__, |_|_| |_|
                          |_|            |___/         
# A Template for Tuner_pluginPlugin, a Filter Plugin
# Generated by the command: plugin -t filter -d tuner_plugin tuner_plugin -o
# Hostname: novo
# Current working directory: /home/leo/Desktop/Workspace/dedalus-workspace
# Creation date: 2026-07-17T09:06:09.564+0200
# NOTICE: MADS Version 2.3.1
*/
// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

// other includes as needed here
#include "tuner.hpp"
#include <fstream>
#include <sstream>
#include <chrono>

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "tuner_plugin"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;

// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class Tuner_pluginPlugin : public Filter<json, json> {

public:
  // Don't forget to inherit the constructors of the parent class
  // If you really need to implement your own constructor, make sure to call 
  // the parent constructor. Normally, use set_params() to set the parameters
  // instead of the constructor.
  using Filter::Filter; // inherit constructors

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid, go to process
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    
    if (!_is_tuning_active || _current_phase == TUNE_DONE) return return_type::retry;
            
    int real_idx = 0;
    switch (_current_phase) {
      case TUNE_X: real_idx = 0; break;
      case TUNE_Y: real_idx = 1; break;
      case TUNE_A: real_idx = 3; break;
      case TUNE_C: real_idx = 4; break;
    }

    if (topic == "machine" && input.contains("position")) {
      if (input["position"].is_array() && input["position"].size() > real_idx) {
        
        float real = input["position"][real_idx];
        _tuner.log_data(_target_k_minus_1, real);
        _last_feedback_time = chrono::steady_clock::now();
        if (std::abs(_target_k_minus_1 - _last_target) < 0.0001f) {
          _stationary_counter++;
        } else {
          _stationary_counter = 0;
        }
        _last_target = _target_k_minus_1;
        if (_stationary_counter > 500 && _tuner.full_buffer()) {
          return return_type::success; 
        }
        
      }
    }
    return return_type::retry;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  // Return types:
  // return_type::success: result is published
  // return_type::retry: don't publish, go to next loop
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: _error is traced via register_event, don't publish
  // return_type::critical: execution stops
  return_type process(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();
    if (!_is_tuning_active) return return_type::retry;
    if (_iter_state == PLAYING_CSV) {
      
      if (_csv_idx < _current_trajectory.size()) {

        _current_csv_setpoint = _current_trajectory[_csv_idx++];
        _target_k_minus_1 = _target_k;
        _target_k = _current_csv_setpoint;
        out["spi_input"]["z"] = 0.0f;
        out["spi_input"]["vx"] = 0.0f;
        out["spi_input"]["vy"] = 0.0f;

        if(_current_phase == TUNE_X){
          out["spi_input"]["x"] = _current_csv_setpoint;
          out["spi_input"]["y"] = 0.0f;
          out["spi_input"]["a"] = 0.0f;
          out["spi_input"]["c"] = 0.0f;
        
        } else if(_current_phase == TUNE_Y){
          out["spi_input"]["y"] = _current_csv_setpoint;
          out["spi_input"]["x"] = 0.0f;
          out["spi_input"]["a"] = 0.0f;
          out["spi_input"]["c"] = 0.0f;
        
        } else if(_current_phase == TUNE_A){
          out["spi_input"]["a"] = _current_csv_setpoint;
          out["spi_input"]["x"] = 0.0f;
          out["spi_input"]["y"] = 0.0f;
          out["spi_input"]["c"] = 0.0f;

        } else if(_current_phase == TUNE_C){
          out["spi_input"]["c"] = _current_csv_setpoint;
          out["spi_input"]["x"] = 0.0f;
          out["spi_input"]["y"] = 0.0f;
          out["spi_input"]["a"] = 0.0f;
        }

      } else {
        _iter_state = WAITING_SETTLE;
      }
    }
    
    else if (_iter_state == WAITING_SETTLE) {
      auto now = chrono::steady_clock::now();
      auto elapsed_ms = chrono::duration_cast<chrono::milliseconds>(now - _last_feedback_time).count();
      if (elapsed_ms > 1000) {
        _iter_state = RUN_ADAM;
      }
    }
    
    else if (_iter_state == RUN_ADAM) {
      
      TuningParams old_params = _tuner.get_p();
      TuningParams new_params = _tuner.process_iteration();
      float current_cost = _tuner.get_last_cost();
      _glob_counter++;

      // check tolerance
      bool target_reached = (current_cost < 0.05f);
      float delta_kp = abs(new_params.kp - old_params.kp);
      float delta_kv = abs(new_params.kv - old_params.kv);
      bool parameters_stagnated = (delta_kp < 0.005f && delta_kv < 0.001f);
      bool timeout_reached = (_glob_counter > 30);

      if (target_reached || parameters_stagnated || timeout_reached) {
        // next axis
        switch(_current_phase){
          case TUNE_X: _current_phase = TUNE_Y; break;
          case TUNE_Y: _current_phase = TUNE_DONE; _is_tuning_active = false; break;
          case TUNE_A: _current_phase = TUNE_C; break;
          case TUNE_C: _current_phase = TUNE_DONE; _is_tuning_active = false; break;
        }

        if (_current_phase != TUNE_DONE) {
          setup_tuner_for_current_phase(); 
        }
      } 
      
      _tuner.reset();
      _stationary_counter = 0;
      _csv_idx = 0;
      _iter_state = PLAYING_CSV;

      out["command"] = "update_pids";
      out["axis"] = (int)_current_phase;
      out["kp"] = new_params.kp;
      out["ki"] = new_params.ki;
      out["kd"] = new_params.kd;
      out["kv"] = new_params.kv;
      out["ka"] = new_params.ka;
    }

    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }
  
  void set_params(const json &params) override {
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Filter::set_params(params);

    setup_tuner_for_current_phase();

    // provide sensible defaults for the parameters by setting e.g.
    _params["some_field"] = "default_value";
    // more here...

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(params);
      
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {};
    
  };

private:

  enum TuningPhase {
    TUNE_X,
    TUNE_Y,
    TUNE_A,
    TUNE_C,
    TUNE_DONE
  };
 
  enum IterationState { PLAYING_CSV, WAITING_SETTLE, RUN_ADAM };
  IterationState _iter_state = PLAYING_CSV;
  TuningPhase _current_phase = TUNE_X;
  Tuner _tuner = Tuner({100.0f, 0.01f, 0.001f, 20.0f, 0.01f});
  float _last_target = 0.0f;
  int _stationary_counter = 0;
  bool _is_tuning_active = true;
  double _glob_counter = 0;
  float _target_k_minus_1 = 0.0f;
  float _target_k = 0.0f;
  vector<float> _current_trajectory;
  size_t _csv_idx = 0;
  float _current_csv_setpoint = 0.0f;
  chrono::steady_clock::time_point _last_feedback_time;

  // load csv
  void load_csv_trajectory(const string& filename, int column_idx) {
    _current_trajectory.clear();
    _csv_idx = 0;
    ifstream file(filename);
    string line;
    
    if (file.is_open()) {
      while (getline(file, line)) {
        if (line.empty()) continue;

        stringstream ss(line);
        string token;
        int current_col = 0;
        bool found = false;

        while(getline(ss, token, ',')){
          if(current_col == column_idx){
            try{
              token.erase(remove(token.begin(), token.end(), '\r'), token.end());
              _current_trajectory.push_back(stof(token));
              found = true;
            }
            catch(...){}
            break;
          }
          current_col++;
        }
      }

      cout << "Loaded " << _current_trajectory.size() 
           << " setpoint from " << filename << endl;

    } else {
      cout << "Error while opening file: " << filename << endl;
    }
  }

  // fly function for selecting axes
  void setup_tuner_for_current_phase() {
    map<string, TuningBounds> bounds;
    string csv_file;
    int csv_column = 0;

    if (_current_phase == TUNE_Y || _current_phase == TUNE_X) {
      bounds["kp"] = {0.0f, 50.0f};
      bounds["ki"] = {0.0f, 10.0f};
      bounds["kd"] = {0.0f, 500.0f};
      bounds["kv"] = {0.0f, 5.0f};
      bounds["ka"] = {0.0f, 2.0f};
    } else {
        bounds["kp"] = {0.0f, 50.0f};
        bounds["ki"] = {0.0f, 0.0f};
        bounds["kd"] = {0.0f, 0.0f};
        bounds["kv"] = {0.0f, 0.0f};
        bounds["ka"] = {0.0f, 2.0f};
    }

    if (_current_phase == TUNE_X){
      csv_file = "traj_x.csv";
      csv_column = 1;
      cout << "fetch traj_x.csv" << endl;
    } 
    else if (_current_phase == TUNE_Y){
      csv_file = "traj_x.csv";
      csv_column = 1;
    }
    else if (_current_phase == TUNE_A){
      csv_file = "traj_a.csv";
      csv_column = 3;
    }
    else if (_current_phase == TUNE_C){
      csv_file = "traj_c.csv";
      csv_column = 4;
    }
    
    _tuner.set_bounds(bounds);
    _tuner.reset();
    _glob_counter = 0;

    load_csv_trajectory(csv_file, csv_column);
    if (_current_trajectory.empty()) {
        cout << "No data loaded" << endl;
        _is_tuning_active = false;
        return;
    }
    _last_feedback_time = chrono::steady_clock::now();
  }
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(Tuner_pluginPlugin, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  Tuner_pluginPlugin plugin;
  json params;
  json input, output;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Set input data
  input["data"] = {
    {"AX", 1},
    {"AY", 2},
    {"AZ", 3}
  };

  // Set input data
  plugin.load_data(input);
  cout << "Input: " << input.dump(2) << endl;

  // Process data
  plugin.process(output);
  cout << "Output: " << output.dump(2) << endl;


  return 0;
}

